import { Bot, BarChart, ShieldCheck, Code, Hospital, Landmark, Factory, ShoppingCart, Cpu, Server, Lock, ScreenShare } from 'lucide-react';

export const NAV_LINKS = [
  { href: '/', label: 'Home' },
  { href: '/services', label: 'Services' },
  { href: '/about', label: 'About Us' },
  { href: '/contact', label: 'Contact' },
];

export const HOME_METRICS = [
  { value: '100+', label: 'Projects Completed' },
  { value: '98%', label: 'Client Satisfaction' },
  { value: '15+', label: 'Years of Experience' },
  { value: '50+', label: 'Happy Clients' },
];

export const HOME_SERVICES = [
  { 
    title: 'ISO Consultancy', 
    description: 'Achieve and maintain ISO compliance with our expert guidance and support.',
    imageId: 'service-iso',
  },
  { 
    title: 'AI & Automation', 
    description: 'Leverage artificial intelligence to automate processes and unlock new efficiencies.',
    imageId: 'service-ai',
  },
  { 
    title: 'Security & SIEM', 
    description: 'Protect your digital assets with our advanced security and SIEM solutions.',
    imageId: 'service-security',
  },
];

export const SERVICES = [
  {
    icon: BarChart,
    title: "ISO Consultancy",
    description: "Our expert ISO consultancy services guide your organization through the complexities of certification. We help you establish robust management systems, ensuring compliance with international standards, improving operational efficiency, and enhancing your market credibility.",
    technologies: ["ISO 9001", "ISO 27001", "ISO 14001", "ISO 45001"]
  },
  {
    icon: Bot,
    title: "AI & Automation",
    description: "Transform your business with our cutting-edge AI and automation solutions. We specialize in developing custom AI models, implementing machine learning algorithms, and automating workflows to boost productivity, reduce costs, and drive data-driven decision-making.",
    technologies: ["Python", "TensorFlow", "PyTorch", "Scikit-learn", "RPA"]
  },
  {
    icon: ShieldCheck,
    title: "Security & SIEM",
    description: "Safeguard your digital assets with our comprehensive security services. We offer everything from vulnerability assessments to implementing Security Information and Event Management (SIEM) systems, providing real-time analysis of security alerts generated by your applications and infrastructure.",
    technologies: ["Splunk", "QRadar", "LogRhythm", "Penetration Testing", "Firewall Management"]
  },
  {
    icon: Code,
    title: "Custom Software Development",
    description: "From concept to deployment, we build bespoke software solutions tailored to your unique business needs. Our team follows agile methodologies to deliver high-quality, scalable, and maintainable software that provides a competitive edge.",
    technologies: ["React", "Node.js", "Java", "PostgreSQL", ".NET Core"]
  },
];

export const HOME_INDUSTRIES = [
  "Healthcare",
  "Finance",
  "Manufacturing",
  "Retail",
  "Education",
  "Government",
  "Technology",
  "Logistics",
];

export const INDUSTRIES = [
  {
    name: 'Healthcare',
    icon: Hospital,
    useCases: [
      {
        title: 'AI-Powered Diagnostics',
        description: 'Implementing machine learning models to analyze medical imaging, leading to faster and more accurate diagnoses.',
      },
      {
        title: 'ISO 13485 Compliance',
        description: 'Assisting medical device manufacturers in achieving ISO 13485 certification for quality management systems.',
      },
    ],
  },
  {
    name: 'Finance',
    icon: Landmark,
    useCases: [
      {
        title: 'Algorithmic Trading',
        description: 'Developing AI-driven trading bots that execute trades based on complex market analysis and predictive modeling.',
      },
      {
        title: 'ISO 27001 for Data Security',
        description: 'Helping financial institutions implement information security management systems to protect sensitive customer data.',
      },
    ],
  },
  {
    name: 'Manufacturing',
    icon: Factory,
    useCases: [
      {
        title: 'Predictive Maintenance',
        description: 'Using IoT sensors and AI to predict equipment failures before they happen, reducing downtime and maintenance costs.',
      },
      {
        title: 'ISO 9001 for Quality Control',
        description: 'Streamlining production processes to meet ISO 9001 standards, ensuring consistent product quality.',
      },
    ],
  },
  {
    name: 'Retail',
    icon: ShoppingCart,
    useCases: [
      {
        title: 'Personalized Customer Experiences',
        description: 'Leveraging AI to analyze customer behavior and provide personalized product recommendations and offers.',
      },
      {
        title: 'Supply Chain Automation',
        description: 'Automating inventory management and logistics to ensure products are always in stock and delivered efficiently.',
      },
    ],
  },
];

export const TECH_STACK = [
  {
    category: 'AI & ML',
    icon: Cpu,
    imageId: 'tech-ai-ml',
    items: ['TensorFlow', 'PyTorch', 'Scikit-learn', 'Keras', 'OpenCV', 'Pandas', 'NumPy'],
  },
  {
    category: 'Backend & Cloud',
    icon: Server,
    imageId: 'tech-backend',
    items: ['Node.js', 'Python', 'Java', '.NET', 'AWS', 'Azure', 'Google Cloud', 'Docker', 'Kubernetes'],
  },
  {
    category: 'Security & SIEM',
    icon: Lock,
    imageId: 'tech-security',
    items: ['Splunk', 'QRadar', 'LogRhythm', 'Nessus', 'Metasploit', 'Wireshark'],
  },
  {
    category: 'Frontend',
    icon: ScreenShare,
    imageId: 'tech-frontend',
    items: ['React', 'Next.js', 'Vue.js', 'Angular', 'TypeScript', 'Tailwind CSS'],
  },
];
